#!/usr/bin/env python

from pylab import imshow

def density_plot(two_dimensional, horiz, vert):
    """
    Display a 2D density plot - like imshow, but with 
    axes labels corresponding to the two axes provided.

    This will only be accurate for regularly-spaced
    x and y axes (e.g., as generated by arange or linspace).

    two_dimensional: data to plot. shape: (M, N)
    horiz: x-axis. should have length N.
    vert: y-axis. should have length M.

    """
    ext = [horiz[0], horiz[-1], vert[0], vert[-1]]
    # this provides axes labels. Unfortunately it also changes
    # the aspect ratio, so we need to stretch it back.
    asp = (ext[1] - ext[0]) / (ext[3] - ext[2])
    asp /=  float(len(horiz))/ len(vert)
    # the first step alone gets us back to a square image aspect.
    # the second will restore the native aspect ratio of the array.
    imshow(two_dimensional, extent=ext, aspect = asp, origin='lower')


